# Stages #
stages:
  - build

## Build Jobs ##

build_pa11y:
  image: docker:24.0.7-dind-alpine3.19
  stage: build
  services:
    - docker:24.0.7-dind-alpine3.19
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/pa11y:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add git
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG